// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function Reorder(arg1) {
  return window['go']['main']['App']['Reorder'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
