// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFiles():Promise<Array<main.FileEntry>>;

export function Reorder(arg1:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;
